name: pg-demo

services:
  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r@#$
      POSTGRES_USER: postgres
      POSTGRES_DB: npgfinal
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - database:/var/lib/postgresql/data 
      - ./script.sql:/docker-entrypoint-initdb.d/database.sql
  
  db-admin:
    image: dpage/pgadmin4:latest
    container_name: database-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "db@balta.io"
      PGADMIN_DEFAULT_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  database:
  pgadmin: